### ISSUE TITLE
Right Click Filter Generates Invalid Query

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#1864]
When the only item in the query is an aggregation operator, the pipe is optional. When you append a filter using a right click menu, the code looks for a pipe and adds is before it. When there is no pipe, it appends to the search. This can create invalid queries.

To reproduce, type `fuse` in the search bar and submit. Then right click any value and click "Filter == value".

Same is true for any aggregation function. Before closing this issue. Look through the zed operator definitions and write tests for all of them.

https://user-images.githubusercontent.com/3460638/135927843-c7bce12d-a9ec-42eb-a59c-da77026cb7d4.mp4

**Comment by philrz** [comment]
Verified in Zui commit 2d23f20.

I checked this one during a recent issue scrub. I was able to confirm this problem was still present in GA Brim `v0.31.0` but was gone in GA Zui `v1.0.0` and remains gone as shown in the attached video below.

https://github.com/brimdata/zui/assets/5934157/7fa2e476-d933-4aa2-a4b6-7adf25267787

I confirmed offline with @jameskerr that our right-click behavior has improved enough since then and the language stability has improved such that no additional work (e.g., more tests, as noted above) is needed and hence this can be closed.
