### ISSUE TITLE
Provide Option to Update Later

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2303]
I was on version 0.28 and got the popup to upgrade to 0.29. I clicked "Later", then I ingested a pcap and quit the app. The next time I opened Brim, I was already upgraded to version 0.29.

We either need to:

1. Allow the user to be on the old version until they click "Update" in the popup.
2. Change the wording to indicate they will be updated to the new version automatically.
3. Remove the popup and simply update them the next time they open the app.

**Comment by philrz** [comment]
@jameskerr: This also reminds me of #1211. I've always been somewhat concerned that the day will come that a user will have a strong motivation to want to remain back on an older release and have no way to do it.

**Comment by philrz** [comment]
Verified in Zui Insiders [v1.5.0](https://github.com/brimdata/zui-insiders/releases/tag/v1.5.0).

As shown in the attached video, now after clicking **Later** I can quit the app and when I restart I'm still in the original version. Since the newer release is still available of course I'll get prompted again, and if I want to stop being bothered by this, I can go into the **Settings** menu and choose a different update check behavior such as **Manual**.

https://github.com/brimdata/zui/assets/5934157/61ff1e43-24f4-4ca7-be64-dcd8a2e59be2

Thanks @jameskerr!
