### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by cehuff** [brimdata/zui#2351]
I have difficulty seeing white background screens.  A simply 'dark mode' would suffice for my needs, with black background and white or high contrast color text. 

Many thanks for your though-provoking zson, zed and zq!

**Comment by jameskerr** [comment]
Thanks @cehuff , this sounds like a good idea and I'd love to work on it. We've only got 2 front-end developers at the moment and are busy with some improving some core functionality. But when the right time comes, a dark mode will ship!

**Comment by philrz** [comment]
Here's another request for this from the community Slack:

https://brimdata.slack.com/archives/C010DR0HHMF/p1657017681180799

Also, the original Slack thread that that spawned the initial issue, which had 4 community members speaking up in favor of the idea:

https://brimsec.slack.com/archives/C010DR0HHMF/p1614714363017400

**Comment by philrz** [comment]
Verified in Zui Insiders [1.5.1-9](https://github.com/brimdata/zui-insiders/releases/tag/v1.5.1-9).

The attached video shows switching to Dark Mode on macOS, for example.

https://github.com/brimdata/zui/assets/5934157/f6c9884d-6a01-495e-9032-5694a51d04bd

I know there's been significant interest in this feature over the past couple years. If there's users "subscribed" to this issue that see this update, we'd much appreciate your help testing out the feature, as it was part of a large set of changes to the app. If you're not already familiar with it, [Zui Insiders](https://github.com/brimdata/zui-insiders) is a "daily build" that allows for early beta-style testing of Zui features before they make it into a GA release. You can have Zui Insiders installed separately from your "regular" Zui and it stores data in its own Zed lake, so that way you don't have to worry about the possibility of bugs messing up your production work.

If anyone does try out the feature, please do add a comment here and let us know how that went or speak up on the `#zui-insiders` channel on the [community Slack](https://www.brimdata.io/join-slack/). Thanks!
