### ISSUE TITLE
Request for documentation: manual import of zeek logs

### ISSUE THREAD

**Issue by omnidepp** [brimdata/zui#2407]
Hi everyone,
while brim's pcap analysis is great for many use cases, I would like to use the brim gui to analyse zeek logs which I generate with custom zeek script. 

Could you provide some detailed documentation on how to import multiple zeek logfiles so that the result is similar to what I get when I drop a pcap directly into the brim app? It might just be me, but I'm having a hard time, figuring this out based on the available information.

For example:
- perform correlation across different log files (i.e. tracking an entry in the files.log through http.log to conn.log based on the uid)
- properly parse timestamps (when dragging zeek-json-files to brim, it does not convert the unix ts to a filterable date, this works for tab separated default zeek logs, though)
- properly parse additional fields I have in my zeek logs
- continuous import of further logs into the same pool (i.e. adding a new conn.log every day with only new entries)

Best regards

**Comment by jameskerr** [comment]
Hi @omnidepp , thank you for your questions. Here are some answers:

1. You can select multiple files on your operating system, and drag them all into a new pool. You cannot add data to an existing pool through the app yet. We plan to add that very soon. You can, however, use the zed cli to add data to an existing pool you have in Brim. https://zed.brimdata.io/docs/commands/zed/#28-load
2. The great thing about the zeek format is it supports rich types. Not just the 5 that json supports. If you have JSON logs, you'll need to shape your data to get the types back. One such workflow is import the json into brim, shape it with a query, then export it to zng. Then re-import that zng file. For docs on how to shape data, you can view the casting abilities provided by the zed language https://zed.brimdata.io/docs/language/overview/#614-casts.
3. Another workflow is create a shaper.zed file and use `zq` to shape your data before you import it into brim. https://zed.brimdata.io/docs/commands/zq/

Good luck, and please joins us on Slack to ask specific questions about any of this. https://www.brimdata.io/join-slack/

**Comment by philrz** [comment]
@omnidepp: Here's another layer of detail.

1.  Since you already have Brim installed, note that the `zed` CLI command is already installed as well. Review [https://github.com/brimdata/brim/wiki/Filesystem-Paths](https://github.com/brimdata/brim/wiki/Filesystem-Paths) for the location to find it based on your OS platform. While you can also download and install Zed tools "a la carte". when you're working with the Brim app it's good practice to use the bundled one since they're known to be a version that's compatible with the installed app.  
     
2.  For the specific case of shaping Zeek JSON logs, there's a bunch of docs in the Zed repo under [https://github.com/brimdata/zed/tree/main/zeek](https://github.com/brimdata/zed/tree/main/zeek) that show how it's done. These should work well for "out of the box" Zeek JSON logs and you can easily extend the examples to cover any additional fields you have based on your local customizations.
