### ISSUE TITLE
First Class Sessions

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2467]
This is a ticket to document a new feature where we make the sessions abstraction front and center in the app.

There will be:
- [x] A new sidebar section for opening previous sessions.
- [ ] A way to rename a session.

**Comment by philrz** [comment]
While written in the context of a bug was fixed by the addition of the feature, this functionality is verified in https://github.com/brimdata/zui/pull/3132#issuecomment-2276743784.

The ability to rename Sessions as described above was not covered in the initial implementation in #2467, so I've opened a new issue #3144 as a reminder for us to get to that at some point.

Thanks @jameskerr!
