### ISSUE TITLE
Sidebar Collapse Button Does Not Appear on Windows

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2549]
There's no way to open the sidebar once you've closed it in the UI. You have to use the View menu. It's not ideal.

<img width="624" alt="Screen Shot 2022-09-21 at 2 05 18 PM" src="https://user-images.githubusercontent.com/3460638/191805693-dab036f1-6984-4081-88ce-81cfb6d8c96c.png">

There is also no dividing line between the menu and the tabs. It looks odd.

**Comment by philrz** [comment]
Good find. Strictly speaking the Ctrl-[ hotkey also seems to bring it back, but I agree that having the button is ideal.

**Comment by philrz** [comment]
I've confirmed via binary search that this was fixed starting with Zui commit 9f091b6, which is associated with the changes in #2895. The following video shows that the collapse button now does appear when the left sidebar is closed, making it possible to easily open it back up again. It also shows that there's some different-colored spacing between the menu and the tabs, so that seems to address the "odd" look also cited above.

https://github.com/brimdata/zui/assets/5934157/1a4bf69e-1b9e-4d83-b6e4-fb981921c1d1

Thanks @jameskerr!
