### ISSUE TITLE
"Reset State" causes "yarn start" to exit (appeared at commit 0d33807)

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#2627]
Repro is with Brim commit 2ee639d.

As shown in the attached video, if I'm running the app in Dev mode via `yarn start`, selecting **Window > Reset State** from the pull-down menu causes the `yarn start` to exit. I assume this is unexpected.

https://user-images.githubusercontent.com/5934157/209715634-d3fd16eb-ad01-42ed-a9d3-01b06b32f05e.mp4

While the repro above is with a current Brim commit, I also confirmed via binary search that I first saw this happen at commit 0d33807 which is associated with the changes in #2584.

**Comment by jameskerr** [comment]
Hey Phil, so this is going to be the new normal behavior in development mode. There's no clear way around this because the app exits, causing yarn start to exit too. I'm fine with this since we don't reset state in development that often and it's not a problem with the production build. I recommend we close this.

**Comment by philrz** [comment]
Ok, then I'm fine with that too. It just happened to be a change in behavior that was unexpected and it made it difficult for me to debug other "Reset State" problems, so I assumed it was a bug. Going ahead and closing.
