### ISSUE TITLE
Query Pool  regex support

### ISSUE THREAD

**Issue by AFgh24** [brimdata/zui#2749]
Query Pool  (Running a query for multiple Pools)

1. Running a query for multiple Pools
2. Pool folder capability
3. Query for multiple Pools in one folder

**Comment by philrz** [comment]
Hello @AFgh24. I think most/all of what you've mentioned here is already present. I know we're lacking in comprehensive Zui docs, so I'll point you to some resources.

1. Running a query for multiple pools is possible by using glob/regexp patterns in the `from` operator ([docs](https://zed.brimdata.io/docs/language/operators/from)). By default in Zui when you click to start querying a pool it creates a "pin" with a single `from` referencing the pool you just clicked since querying a single pool is such a common use case. However, you can always delete such a pool pin and replace it with an explicit `from` that references multiple pools, such as in this video where I do `from *` to target all pools. (BTW, while revisiting this functionality just now, I did find a regexp case that didn't behave the way I expected, so I've opened [#4496](https://github.com/brimdata/zed/issues/4496) to look into that. If you spot anything else unusual when trying to use regexps please go ahead and open issues.)

https://user-images.githubusercontent.com/5934157/232615631-c158fd18-2b37-4e2c-a397-da3f3ddb29df.mp4

2. Pool folders are also available in that pools named with a "separator" character are automatically organized by the app so they're treated like folders. The video linked from https://github.com/brimdata/zui/issues/1805#issuecomment-1304838026 shows this feature being used in several ways.

3. If pools have been arranged into a folder, you should be able to write a glob or regexp that targets those pools. For instance, in the attached contrived example, I've got four pools inside of a "folder" by starting each of their names with `foo/`, and I've also got a top-level pool called `foox509`. By creating a regexp in my `from` that matches against the leading `foo/` I'm able to target just those four pools in the folder and exclude the `foox509` one.

https://user-images.githubusercontent.com/5934157/232617364-494148f5-731c-4843-a44d-40219a94b5b5.mp4

Let me know if those address the use cases you had in mind. If you can describe some things you want to achieve that aren't possible with these building blocks, we can go ahead and open new issue(s) for those.

**Comment by AFgh24** [comment]
Thanks is really great

Just one question, I used the following command to search for a text among linear data, it is a test folder, my search text is normal in all pools, but I encountered an error.

![12](https://user-images.githubusercontent.com/124514890/232856001-d170648a-873b-45fa-99db-bdd1841f2a65.png)
![3](https://user-images.githubusercontent.com/124514890/232856019-e3af6b04-f9d3-4704-ad74-10793c02196e.png)

form test | normal
form *| normal

Unfortunately, my knowledge is limited

**Comment by philrz** [comment]
@AFgh24: It looks like you've just got a typo there, having used `form` when you'd want to say `from` (https://zed.brimdata.io/docs/language/operators/from). Setting up similar pools on this end, these both work ok with `from`.

![image](https://user-images.githubusercontent.com/5934157/232860220-a82bd105-6520-4e95-b02a-c555a5c6c4df.png)

![image](https://user-images.githubusercontent.com/5934157/232860286-4cbc661c-05ec-4c64-bbc6-65d96ebbf485.png)

**Comment by philrz** [comment]
@AFgh24: Given your emoji reactions to the most recent comment and not having posted another question since then, I'm going to assume you're working ok with the responses that have been provided and will hence go ahead and close this issue. If you spot something else feel free to comment or open a new issue.
