### ISSUE TITLE
Brimdata/Zui Windows application only shows Details tab and is not responsive to any input

### ISSUE THREAD

**Issue by AMoneim97** [brimdata/zui#2750]
**Describe the bug**
When trying to open the Brimdata/Zui Windows application, only the Details tab is displayed and the application is not responsive to any input.

**Screenshots**
![image](https://user-images.githubusercontent.com/91743675/233348858-3ae18395-a063-44f8-8f00-8e57af198adb.png)

**Desktop Info**
 - OS: [ Windows 10 Pro]
 - Zui Version: Zui 1.0.1

**Comment by philrz** [comment]
@AMoneim97: It looks like you've probably run into a known issue #2730. Since you're on Windows, you should be able to get the main window back by right-clicking the Zui app icon in the Task Bar and selecting **New Window**. We have a fix for this coming up in the next release so it should hopefully not keep happening.

Please do let us know if that fixes it.

**Comment by philrz** [comment]
@AMoneim97: Since we put out a release a long time ago that included a fix for #2730 that matches your reported bug and we've not heard from you at this issue since my last comment, I'm going to go ahead and close this on the assumption you're doing ok now. If you're still having problems though, feel free to comment here or come talk to us on [community Slack](https://www.brimdata.io/join-slack/) and we're happy to help.
