### ISSUE TITLE
Display the number of data of each pool

### ISSUE THREAD

**Issue by AFgh24** [brimdata/zui#2752]
Display the number of data of each pool

I used the following command to do this
**count()**
I think displaying the data record under **Timestamp** is a good option

**Comment by philrz** [comment]
@AFgh24: Thanks for reporting. Indeed, we've been due to redesign that pool summary info page with more detail, so I've started up a new issue #2755 to capture your suggestion along with other ideas we've collected. I'm therefore going to close this one as a duplicate, but please do go ahead and watch/comment on #2755 as appropriate.
