### ISSUE TITLE
When I import some data, there may be bad strings in some entries in the data. Can you let me skip these data and continue importing?

### ISSUE THREAD

**Issue by uxbug** [brimdata/zui#2756]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://zui.brimdata.io/docs/support/Troubleshooting

**Is your feature request related to a problem? Please describe.**
When I import some data, there may be bad strings in some entries in the data. 
At present, zui gives a hint.
```
Ingest Warnings
The data you've attempted to import was not recognized as any supported packet capture or log format. The errors returned by each log parser:

invalid character 'M' looking for beginning of value
```

**Describe the solution you'd like**
When encountering a bad string, I wonder if you can give me a choice to skip this data or automatically encode these data so that I can continue to import subsequent data instead of interrupting the import process.

**Comment by philrz** [comment]
@uxbug: Thanks for filing the issue. Indeed, this is a topic that's come up a couple times before, and we just had a group discussion about it and came up with an idea to address it at the Zed layer that's now being tracked in https://github.com/brimdata/zed/issues/4546.

In the time before that's addressed, there may be other things we could do to help you read your data. Could you say a bit more about the format of your input data? I'm not sure if you're new to Zui, but users have been tripped up sometimes by the app's attempt to "auto-detect" the input format when data is dragged directly into the app. E.g., in this screenshot I've just tried to drag the `/etc/passwd` from my Mac into the app and so each error message line shown explains why it failed to be recognized as any of those formats.

![image](https://user-images.githubusercontent.com/5934157/234374954-6fab41c1-3888-4061-a97b-6ff2ee1b4ae7.png)

Since the error message you shared was the "invalid character ... looking for beginning of value" variety, perhaps your input data was known to be JSON and you were trying to import from the **New Pool** page while picking JSON from the **Format** list? In that case if you just want to get the data in _somehow_ so you can at least do grep-like searches against it as strings, I wanted to make sure you're aware of the "Line" option from that **Format** list, since that would just turn everything into strings based on the newline separator and hence avoid any parsing problems.

At https://github.com/brimdata/zed/issues/4546#issuecomment-1522281860 I also showed an example at the Zed layer of how such strings could be parsed as JSON/ZSON, so you might think about preprocessing with `zq` load before loading, or you could load into Zui as "Line", do the parse inside the app, and chain your other operations on the data after the parse like shown here:

![image](https://user-images.githubusercontent.com/5934157/234379402-d610d5a6-7ef0-4c91-9d3f-47ecaf2cf103.png)

Let me know if any of that helps!

**Comment by uxbug** [comment]
@philrz 
  Thank you for your prompt and enthusiastic response. As a new user of zui, I am thrilled to have discovered such an exceptional tool for handling JSON and displaying data precisely how I want it. I am deeply grateful for the hard work and dedication of the developers behind this remarkable software.
  The issue I encountered occurred when I imported JSON data into zui after converting a CSV file to JSON. Upon careful investigation, I found that the problem was likely due to an issue with the formatting of the JSON data, such as incorrect line breaks or similar errors.
```
{
    "onekey" : "onevalue
    ",
    "twokey" : "twovalue"
}
``
 Alternatively, the problem might have been caused by encountering bad characters within the JSON data, such as:
```
{
    "onekey" : "x0fonevalue",   //hex x0f Invisible
    "twokey" : "twovalue"
}
```
  Currently, I have written a new program to convert CSV to JSON data and made necessary corrections to address the aforementioned issues. As a result, I have successfully imported the data into zui. 
  Once again, I would like to express my gratitude for your response and hope that zui continues to improve and become even more user-friendly.

**Comment by philrz** [comment]
@uxbug: Thanks for the kind words about much you've been enjoying Zui! I've passed word along to our developers and the rest of the Brim team.

Since it sounds like you're loading data ok now, I'm going to go ahead and close this issue, but let us know if anything else comes up. We'd also love to have you join our [community Slack](https://www.brimdata.io/join-slack/) and hear more about what you've managed to do with Zui/Zed and/or trade tips with other users. Ping me on there as `@Phil` any time.
