### ISSUE TITLE
Creating a virtual pool

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#2889]
Creating a virtual pool

![Untitled](https://github.com/brimdata/zui/assets/150426297/061d03a3-3eb0-4d25-905f-3ac66009bda6)

I have a problem to check the log of different software

With the increase in the number of logs due to the different title of the logs as shown in the image below

I encounter problems in some searches. I forget that the titles of some fields are different. Because the number of pools also increases

Is it possible to create a main virtual pool and then define some main field titles and during data import the user has the possibility to choose the connection between this imported field and the main virtual pool

to apply the search only to the main pool rather than using multiple field titles for multiple pools

Connecting different pools to a specific pool for easy searching

**Comment by philrz** [comment]
@SoftTools59654: We've had an inquiry at least once before about this kind of functionality. That's captured in https://github.com/brimdata/zed/issues/4582 which is in the Zed repo because this depends on functionality that exists and could be enhanced at the Zed lake layer before anything more is built on top of it in the Zui app. In response to that first inquiry in https://github.com/brimdata/zed/issues/4582, I wrote up an example there of how something close to this could be achieved today, along with some questions and requests for feedback. It would be great if you could read what's there, see how far it gets you with your specific use case, and add a comment there with any feedback you have from your experience trying it. As you can see when looking at that issue, the person who originally opened it never did respond with any feedback. We tend to only start designing new features if the users that request them stay engaged in helping to make sure what gets built is ultimately what they'll use, so your participation would be helpful.

I've copied your details into https://github.com/brimdata/zed/issues/4582, so I'm going to close this specific Zui issue as a duplicate and we can pick up the discussion over there.
