### ISSUE TITLE
The problem of searching for the next number and character @

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#2910]
The problem of searching for the next number and character @

When an email is searched, for example ( [test File](https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/people/people-1000.csv) )

test19@example.org is displayed in the output, but when one or two numbers are searched after and @ character, the result is not displayed.

![0](https://github.com/brimdata/zui/assets/150426297/59b11b54-0e61-43f8-b940-96dbd8285b02)
![1](https://github.com/brimdata/zui/assets/150426297/0eb61c49-bb1c-4ddf-9aae-8e65b7ea1ea2)

**Comment by philrz** [comment]
@SoftTools59654: Thanks for including the test data.

As the [search expression docs](https://zed.brimdata.io/docs/language/search-expressions) describe, there's multiple ways to construct [search terms](https://zed.brimdata.io/docs/language/search-expressions#search-terms) and one of those could be used here to make your example work.

For instance, it can be quoted as a [string literal](https://zed.brimdata.io/docs/language/search-expressions#string-literal-search-term).

<img width="1023" alt="image" src="https://github.com/brimdata/zui/assets/5934157/ad4ef447-304c-4d08-874a-1515b560c0e2">

Or it could be a [glob](https://zed.brimdata.io/docs/language/search-expressions#glob-search-term).

<img width="1023" alt="image" src="https://github.com/brimdata/zui/assets/5934157/c6daf58d-c89c-4278-9212-9982504d355d">

Or a [regular expression](https://zed.brimdata.io/docs/language/search-expressions#regular-expression-search-term).

<img width="1023" alt="image" src="https://github.com/brimdata/zui/assets/5934157/e959f1e9-de40-49ba-9380-aeb978ff4304">

What you were seeing is a side effect of the [keyword](https://zed.brimdata.io/docs/language/search-expressions#keyword-search-term) shorthand for expressing search terms. These allow you to avoid using the quoting or other syntaxes shown above, but only if the keyword meets the criteria described there for "valid keyword characters" (i.e., ensuring it won't clash with any of the other unquoted language constructs). Per the rules shown there, the leading digit in `19@example.org` means it's no longer parsed as a keyword search term, but it fails to parse as any of the other language constructs either, hence the syntax error you saw.

If you find this too confusing, you could get into the habit of always quoting. However, we find the keyword shorthand is useful much of the time (e.g., so you don't have to worry about matching quotes) which is why it's offered rather than requiring users to always quote search terms.

Let us know if you have any additional questions about that.

**Comment by philrz** [comment]
@SoftTools59654: Based on your emoji reactions to the last comment, I gather you're ok now. 😄  Closing this one.
