### ISSUE TITLE
Suggestion to solve csv import problem (defective)

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#2933]
Suggestion to solve csv import problem (defective)

When importing a csv file, if there is an error in one line, the file will be imported only up to that line or the data will not be imported at all.

My suggestion is that zui reads the last line of data when importing data
And if at the time of error, this last data line was not there, jump to the next line and continue the import
And create the problem lines with the same name as the main pool in a folder, with the difference that it imports the problem lines in a pool with the line name. In this case, we even have access to faulty data and in the form of a line

This is not a professional solution, but most of the data is not standard and this is a big problem for csv import

**Comment by philrz** [comment]
@SoftTools59654: Yes, you are correct that this is an area where we know the tools can be improved. We've already given some thought to a design to address this after other users have brought up the topic in the past. It's yet another problem that we'll have to solve first at the Zed layer and then figure out how to best present the errors in Zui. We've been tracking the thoughts to date on the topic in existing issue https://github.com/brimdata/zed/issues/4546 so I'll suggest that you "subscribe" to that one. I've copied some of your helpful ideas from this issue into a comment there and will be closing this one to consolidate. Feel free to post comments on that issue if you have additional feedback or questions about the approach. Since we've been making other improvements to the readers/writers recently (e.g., https://github.com/brimdata/zed/pull/4889, https://github.com/brimdata/zed/pull/4891) I'm going to discuss with the Dev team if we can boost the priority in this area to maintain momentum since it has indeed come up several times with users now.
