### ISSUE TITLE
Zed union values rendered blank in Detail window

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#2938]
Display the field as empty

While the desired fields have data, but when clicking to open and display the fields, sometimes the fields are displayed empty.

Mostly there are numbers in the fields inside them, this problem is seen more often

![image](https://github.com/brimdata/zui/assets/150426297/0576a7a2-9554-4b68-9eef-229d8aa8ef89)

**Comment by philrz** [comment]
@SoftTools59654: I don't doubt that there's a bug here, but I can't seem to reproduce the issue using just the detail you've been able to provide thus far. For instance, in the attached video I've created input data that looks similar to what you've shown in your screenshot, but when I double-click to bring up the data in a Details window, the value is not blank for me. I'm sure your data has a lot more rows/columns so it's likely that the bug is somehow dependent on something else specific about your data, but it's difficult for me to know what that might be. Can you perhaps provide a sample data set that you've seen that reproduces the problem consistently for you? I know a lot of data is sensitive and can't be shared, but perhaps you could "anonymize" it enough for it to be shared.

Just in case I might be lucky enough to catch it with another random data set, the video also shows the fusing and display in Details of the sample data from https://github.com/brimdata/zed/issues/4514, but once again, it does not reproduce. 

https://github.com/brimdata/zui/assets/5934157/9d010f1f-e9d5-44e2-81c3-895eeee815a9

Thanks for your help in narrowing this down!

**Comment by philrz** [comment]
@SoftTools59654: I think I've figured out what's probably triggering the bug you saw. I couldn't initially reproduce the problem using only the data shown in your screenshot or other random data sets I had on hand. But in thinking about the kinds of Zed values that have caused problems in the past, in this attached video I happened to reproduce the problem successfully at Zui commit ca6ddd3 using this sample `data.csv`:

```
Index,Customer Id
1966079,54b0eFA66A2fE15
1900543,fE24fDD0D042fFE
123,456
```

https://github.com/brimdata/zui/assets/5934157/3a2dc08f-5ec5-4c3c-93f4-90e4b4234ba4

What seems to be important in reproducing the problem is that across the data set the `Customer Id` field has values of both string type and numeric type (i.e., the final row in my `data.csv` triggers the problem), such that after `fuse` is applied the overall data type for `Customer Id` becomes a Zed [union data type](https://zed.brimdata.io/docs/formats/zed#25-union).

![image](https://github.com/brimdata/zui/assets/5934157/c5a0202a-2791-434a-9c13-ec95d448d974)

Therefore it looks like we probably have a Zui bug here we can fix that's specific to rendering values of union types. If you've seen this same effect with other types, please do share the details so we can fix those as well.

**Comment by philrz** [comment]
Verified in Zui commit e73f73b.

As shown in the attached video, when we repeat the repro steps with the same `data.csv` test data, the post-`fuse` union values are no longer blank in the **Detail** window or side panel.

https://github.com/brimdata/zui/assets/5934157/160b63d8-0f4d-42a7-a00e-8ed860d71da4
