### ISSUE TITLE
Zui Time zone settings don't work.

### ISSUE THREAD

**Issue by burpheart** [brimdata/zui#2946]
**Describe the bug**

<img width="904" alt="20231221123221" src="https://github.com/brimdata/zui/assets/35721255/a2846dbb-d940-4fdc-b51b-5e3814e6bd5d">
I'm trying to import a JSONL file with RFC 3339 string key with timezone and use the time method to force the conversion to UTC time.

<img width="455" alt="20231221123524" src="https://github.com/brimdata/zui/assets/35721255/97c907c5-92de-4158-84a6-2211ddfb78a6">

<img width="931" alt="20231221123515" src="https://github.com/brimdata/zui/assets/35721255/880a3ccb-12e8-402c-90e7-3613fbb32561">
But I realized that the time on the timeline is not displayed according to the time zone set by ZUI.

**Expected behavior**
The time on the timeline should be displayed using the set time zone. It would be nice if the time in the data table also had a time zone.

**Desktop Info**
[Please complete the following information]
 - OS: Windows
 - Zui Version: 1.5.0

**Comment by philrz** [comment]
Hello @burpheart. Yes, this is a known issue, and we're probably due to finally do something about it. I've copied your comments over to an existing issue #1057 where we've consolidated the user reports to date on this topic, and I've added a comment there at https://github.com/brimdata/zui/issues/1057#issuecomment-1869785288 summarizing the current state of things and making the argument for this to be fixed. We've got limited development resources working on Zui and a lot of active priorities so I'm not sure how soon this work will be completed, but I'm going to push for something sooner than later. Please do "subscribe" to #1057 so you can see when the enhancement lands. Thanks for your interest in Zui!
