### ISSUE TITLE
Hard disk space occupied by a zng file

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#3019]
Hard disk space occupied by a zng file

Although the size of the imported files is 296MB, the space is used. It is 780 MB

Or the wrong original volume is displayed. or an additional file

There is a zng file that is the same size as the entire pool. And the number of split files of the pool is the same size

I also tested in high volume files, even a 10 GB pool had the same problem, one file with a volume of 10 GB and several small files with a total volume of 10 GB.

What is this file with a large volume, is it possible to delete it?

![image](https://github.com/brimdata/zui/assets/150426297/9d15ab49-ae34-4040-aa16-bc45a5bb69e6)

**Comment by philrz** [comment]
@SoftTools59654: It sounds like you may not understand the Zed lake concept. When you import files into Zui, the data gets broken up into [data objects](https://zed.brimdata.io/docs/lake/format#immutable-objects) stored in the lake. This storage is separate from whatever file(s) you may have originally imported into Zui. If you need to free up space on your workstation and no longer need the original file(s), you can delete them because once data is imported Zui only accesses the data in the lake directory.

While we appreciate that you're taking an interest in the Zed internals, opening bugs against the Zui repo is not an effective way to learn this. If you have further inquiries like these, my recommendation is that you first invest some time in understanding what's in the Zed documentation, with an emphasis on:

* https://zed.brimdata.io/docs/lake/format
* https://zed.brimdata.io/docs/commands/zed
* https://zed.brimdata.io/docs/tutorials/zed

At that point if you have further questions about the Zed lake I'd recommend fielding your questions via the `#zed` channel of the [community Slack](https://www.brimdata.io/join-slack/) system. You're also welcomed to still open GitHub Issues if you find issues or have feature requests about the Zed lake, but if so please do so in the [Zed repo](https://github.com/brimdata/zed) and in a way that reflects that you've read and made an attempt to understand the materials we've already made available. If you open bugs please try to provide publicly-available data and specific steps to reproduce the issue. Thank you.
